### PR TITLE
Release/2.0.0

### PR DESCRIPTION
**Pull request by akaila-splunk**
### New features and APIs
* Callbacks have been removed and instead we are returning Promises which enables users to use Async/Await features of JS. ([PR#162](https://github.com/splunk/splunk-sdk-javascript/pull/162)) 
* Added 'response_timeout' parameter which enables user to specify the timeout for a particular API call.
* Removed Async.js file and the required methods have been migrated to Utils.js following the Promise structure.

### Minor changes
* Update doc generation logic in GitHub ci ([PR#167](https://github.com/splunk/splunk-sdk-javascript/pull/167))
* Updated minimist library versions ([PR#166](https://github.com/splunk/splunk-sdk-javascript/pull/166))
* Added feature that allows to update ACL properties of an entity ([PR#170](https://github.com/splunk/splunk-sdk-javascript/pull/170))
* Support for updated SDK examples ([PR#171](https://github.com/splunk/splunk-sdk-javascript/pull/171))

### CODE REVIEW

**Comment by ncanumalla-splunk** [comment]
@ashah-splunk Can we add a section in the Readme, describing the Promise pattern with a snippet the way we did here: https://github.com/splunk/splunk-sdk-javascript/issues/155. Thanks.

**Review by fantavlik — APPROVED** [review]
🎉

**Comment by akaila-splunk** [comment]
> @ashah-splunk Can we please add a section in the Readme, describing the Promise pattern with a snippet the way we did here: #155. Thanks.

Hi @ncanumalla-splunk , we have updated REAMDE.md file as per the discussion. Please review it and let us know if any other changes are required.

**Comment by ncanumalla-splunk** [comment]
Looks good to me. Thanks!

**Pull request merged**
